default_job = "run"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

# Run clippy on the default target
[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false

# You can run your application and have the result displayed in bacon,
# if it makes sense for this crate.
[jobs.run]
command = [
    "just", "run",
]
need_stdout = true
allow_warnings = true
background = true
watch = [
  "content/",
  "static/",
  "styles/"
]
