name: Test Suite

on:
  workflow_dispatch:
  push:

jobs:
  cargo-check:
    name: Cargo Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cargo Check
        run: cargo check --all

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@master
        id: typos
        continue-on-error: true
        with:
          files: ./content

      - name: Fail when typos are found
        if: ${{ steps.typos.outcome != 'success' }}
        run: "exit 1"
